practice/apps/courses/urls.py
from django.conf.urls import url, include
from .views import CoursesListView, CourseDetailView, CourseInfoView, CommentsView, AddCommentsView\
    , VideoPlayView
urlpatterns = [
    url(r'^list', CoursesListView.as_view(), name="courses_list"),  # 课程列表
    url(r'^detail/(?P<course_id>\d+)$', CourseDetailView.as_view(), name="course_detail"),  # 课程详情
    url(r'^info/(?P<course_id>\d+)$', CourseInfoView.as_view(), name="course_video"),
    url(r'^comment/(?P<course_id>\d+)$', CommentsView.as_view(), name="course_comment"),


    # 用户添加评论(js访问)
    url(r'^add_comment/$', AddCommentsView.as_view(), name="add_comments"),

    url(r'^video/(?P<video_id>\d+)$', VideoPlayView.as_view(), name="video_play"),
]

practice/apps/organization/urls.py
from django.conf.urls import url, include
from .views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView, \
    AddFavView, TeachersListView, TeacherDetailView


urlpatterns = [
    url(r'^list$', OrgView.as_view(), name="org_list"),
    url(r'^add_ask$', AddUserAskView.as_view(), name="add_ask"),
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name="org_home"),
    url(r'^org_course/(?P<org_id>\d+)$', OrgCourseView.as_view(), name="org_course"),
    url(r'^desc/(?P<org_id>\d+)$', OrgDescView.as_view(), name="org_desc"),
    url(r'^teacher/(?P<org_id>\d+)$', OrgTeacherView.as_view(), name="org_teacher"),



    # 机构收藏
    url(r'^add_fav/$', AddFavView.as_view(), name="org_add_fav"),

    # 讲师列表
    url(r'^teachers/list$', TeachersListView.as_view(), name="teachers_list"),
    # 讲师详情
    url(r'^teachers/detail/(?P<teacher_id>\d+)$', TeacherDetailView.as_view(), name="teachers_detail"),

]

practice/apps/users/urls.py
from django.conf.urls import url, include
from .views import UserInfoView, UploadImageView, UpdatePwdView, MyCoursesView, MyFavoriteOrgsView, \
    MyFavoriteTeachersView, MyFavoriteCoursesView, MyMessageView
urlpatterns = [
    url(r'^info', UserInfoView.as_view(), name="user_info"),  # 课程列表
    url(r'^image/upload', UploadImageView.as_view(), name="image_upload"),  # 用户头像上传
    url(r'^pwd/update', UpdatePwdView.as_view(), name="pwd_update"),  # 个人中心密码修改

    url(r'^my/courses', MyCoursesView.as_view(), name="my_courses"),  # 用户收藏课程
    url(r'^my_fav/orgs', MyFavoriteOrgsView.as_view(), name="my_fav_orgs"),  # 用户收藏的机构
    url(r'^my_fav/teachers', MyFavoriteTeachersView.as_view(), name="my_fav_teachers"),  # 用户收藏讲师
    url(r'^my_fav/courses', MyFavoriteCoursesView.as_view(), name="my_fav_courses"),  # 用户收藏课程
    url(r'^my/message', MyMessageView.as_view(), name="my_message"),  # 用户消息



]

practice/practice/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
from django.views.generic import TemplateView  # 表示处理静态文件,引入TemplateView类
import xadmin
from django.views.static import serve  # 引入处理静态文件的函数
from practice.settings import MEDIA_ROOT #STATIC_ROOT  # 引入MEDIA根目录, STATIC根目录

# from users.views import user_login  # 引入基于函数的登录验证
from users.views import IndexView, LoginView, RegisterView, ActiveUserView, ForgetPwdView, \
    ResetView, LogoutView  # 引入基于类的登录验证
from organization.views import OrgView
urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url('^$', IndexView.as_view(), name="index"),  # 这里用TemplateView类中的as_view方法
    # url('^user_login/$', user_login, name="user_login")  # 基于函数的登录验证
    url('^user_login/', LoginView.as_view(), name="user_login"),  # 注意调用基于类的方法时要加上括号

    url('^user_logout/', LogoutView.as_view(), name="user_logout"),

    url('^register/', RegisterView.as_view(), name="user_register"),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(P<active_code>.*)/$', ActiveUserView.as_view(), name="user_active"),  # 注意url中的active_code是参数，
                                                                                         # 需要传到视图函数中,复习正则表达式
    url(r'^forget/$', ForgetPwdView.as_view(), name="forget_pwd"),
    url(r'^reset/(P<reset_code>.*)/$', ResetView.as_view(), name="reset_pwd"),

    # 用户组
    url(r'^users/', include('users.urls', namespace='users')),

    # 机构组
    url(r'^org/', include('organization.urls', namespace='org')),

    # 课程组
    url(r'^courses/', include('courses.urls', namespace='courses')),


    # 配置上传文件的访问处理，因为有的图片是放在media中，不是static中，所以要重新配置
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),


    # url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),





]

# 全局404页面配置，名字必须叫handler404
handler404 = 'users.views.page_not_found'

# 全局500页面配置，名字必须叫handler500
handler404 = 'users.views.page_not_found'

practice/apps/users/forms.py
from django import forms
from .models import UserProfile
from captcha.fields import CaptchaField


# 自定义表单验证，在这里先对前端提交的表单进行校验，校验通过再去查询数据库，从而减轻数据库的负担
class LoginForm(forms.Form):
    username = forms.CharField(required=True)  # 注意这里字段的名称必须要和前端页面的input标签中的name的名称一直才能保证正确对应
    password = forms.CharField(required=True)


# 注册表单
class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)  # 默认的Email格式要符合
    password = forms.CharField(required=True)
    captcha = CaptchaField(error_messages={"invalid": "验证码错误"})


# 密码找回表单
class ForgetPwdForm(forms.Form):
    email = forms.EmailField(required=True)  # 默认的Email格式要符合
    password = forms.CharField(required=True)
    captcha = CaptchaField(error_messages={"invalid": "验证码错误"})


# 修改密码表单
class ModifyPwdForm(forms.Form):

    password1 = forms.CharField(required=True)
    password2 = forms.CharField(required=True)
    captcha = CaptchaField(error_messages={"invalid": "验证码错误"})


class UploadImageForm(forms.ModelForm):
    """
    用户头像表单
    """
    class Meta:
        model = UserProfile # 表示针对UserProfile模型
        fields = ['image']  # 挑选想要的字段，只要求有图片就行

practice/templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>链接失效</title>
</head>
<body>
<P>
    该激活链接已失效，请重新获取。
</P>
</body>
</html>

practice/templates/course-detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}课程详情{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页></a></li>
                <li><a href="{% url 'courses:courses_list' %}">科目列表></a></li>
                <li>课程详情</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <section>
	<div class="wp">
		<div class="groupPurchase_detail detail">
			<div class="toppro">
				<div class="left">
					<div class="picbox">
						<div class="tb-booth tb-pic">
							<img width="440" height="445" src="{{ MEDIA_URL }}{{ course.image }}" class="jqzoom" />
						</div>

					</div>
					<div class="des">
						<h1 title="django 从入门到精通体验开始了">{{ course.name }}</h1>
						<span class="key">{{ course.desc }}</span>
						<div class="prize">
							<span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
							<span class="fr">学习人数：{{ course.students }}</span>
						</div>
						<ul class="parameter">
							<li><span class="pram word3">时&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;长：</span><span>{{ course.learn_times }}</span></li>
                            <li><span class="pram word3">章&nbsp;节&nbsp;数：</span><span>{{ course.get_zj_nums }}</span></li>
                            <li><span class="pram word3">课程类别：</span><span title="">{{ course.category }}</span></li>
							<li class="piclist"><span class="pram word4">学习用户：</span>
                                {% for learn_user in course.get_learn_users %}
                                    <span class="pic"><img width="40" height="40" src="{{ MEDIA_URL }}{{ learn_user.user.image }}"/></span>
                                {% endfor %}
							</li>
						</ul>
						<div class="btns">
							<div class="btn colectgroupbtn"  id="jsLeftBtn">
                                  {% if has_fav %}收藏成功{% else %}收藏{% endif %}
                            </div>
                                <div class="buy btn"><a style="color: white" href="{% url 'courses:course_video' course.id %}">开始学习</a></div>
						</div>
					</div>
                    <div class="group-share-box">
                        <div class="bdsharebuttonbox"
                             data-text="django开始了"
                             data-desc="我在#慕课网#发现了"
                             data-comment=""
                             data-url="/group/groupdetail/15/">
                            <span class="fl">分享到：</span>
                            <a href="#" class="bds_more" data-cmd="more"></a>
                            <a title="分享到QQ空间" href="#" class="bds_qzone" data-cmd="qzone"></a>
                            <a title="分享到新浪微博" href="#" class="bds_tsina" data-cmd="tsina"></a>
                            <a title="分享到腾讯微博" href="#" class="bds_tqq" data-cmd="tqq"></a>
                            <a title="分享到人人网" href="#" class="bds_renren" data-cmd="renren"></a>
                            <a title="分享到微信" href="#" class="bds_weixin" data-cmd="weixin"></a>
                        </div>
                    </div>
				</div>
				<div class="right">
					<div class="head">
						<h1>授课机构</h1>
						<p>世界名校，课程权威</p>
					</div>
					<div class="pic">
                        <a href="/company/14/">
                            <img width="150" height="80" src="{{ MEDIA_URL }}{{ course.course_org.image }}"/>
                        </a>
                    </div>
					<a href="/company/14/">
                        <h2 class="center" title="清华大学">{{ course.course_org.name }}</h2>
                    </a>
					<div class="btn  notlogin
					     "data-favid="14" id="jsRightBtn">
                         {% if has_fav %}收藏成功{% else %}收藏{% endif %}
                    </div>
					<div class="clear">
						<ul>
                            <li>
                                <span>课 &nbsp;程&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   {{ course.course_org.course_nums }}</span>
                            </li>
                            <li>
                                <span>教 &nbsp;师&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  {{ course.course_org.get_teacher_nums }}</span>
                            </li>
							<li>所在地区：&nbsp;&nbsp;{{ course.course_org.city.name }}</li>
							<li>认&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;证&nbsp;:
                                &nbsp;&nbsp;
                                <img src="{% static "images/gold.png" %}"/>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
    <section>
	<div class="wp">
		<div class="list groupPurchase_detail_pro">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active">课程详情</li>
					</ul>
				</div>
				<div class="tab_cont tab_cont1">

					{{ course.detail }}
				</div>
				<div class="tab_cont tab_cont2" >
					<div class="comment">
						<div class="comenlist">

	                    </div>
					</div>
				</div>
			</div>
			<div class="right layout">
				<div class="head">相关课程推荐</div>
                {% for course in related_course %}
                         <div class="group_recommend">


                        <dl>
                            <dt>
                                <a target="_blank" href="">
                                    <img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <a target="_blank" href="{% url 'courses:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">学习时长：<i class="key">{{ course.learn_times }}</i></span>
                            </dd>
                        </dl>



                </div>
                    {% endfor %}

			</div>
		</div>
	</div>
</section>


{% endblock %}

{% block custom_js %}
<script type="text/javascript">
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'org:org_add_fav' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            //因为没有form，无法设置csrftoken，只能在这里设置
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="{% url 'user_login' %}";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$(document).ready(function() {
    $('#jsRightBtn').on('click', function(){
        add_fav($(this), {{ course.course_org.id }}, 2)
    });

    $('#jsLeftBtn').on('click', function(){
    add_fav($(this), {{ course.id }}, 1);
    });
});
</script>
{% endblock %}

practice/templates/course-list.html
{% extends 'base.html' %}
{% block title %}科目列表{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>科目列表</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="{% ifequal sort "" %}active{% endifequal %}"><a href="?sort=">最新 </a></li>
						<li class="{% ifequal sort "hot" %}active{% endifequal %}"><a href="?sort=hot">最热门</a></li>
						<li class="{% ifequal sort "students" %}active{% endifequal %}"><a href="?sort=students">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">
                            {% for course in all_courses.object_list %}
                            <div class="box">
                                <a href="{% url 'courses:course_detail' course.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'courses:course_detail' course.id %}">
                                        <h2>{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="{% url 'org:org_home' course.course_org.id %}"><span class="fl">{{ course.course_org.name }}</span></a>
                                    <span class="star fr  notlogin
                                        " data-favid="15">
                                        {{ course.fav_nums }}
                                    </span>
                                </div>
                            </div>
                            {% endfor %}
					</div>
                    <div class="pageturn">
                        <ul class="pagelist">
{#                                <li class="active"><a href="?page=1">1</a></li>#}
{#                                <li><a href="?page=2" class="page">2</a></li>#}
{#                                <li class="long"><a href="?page=2">下一页</a></li>#}
    {% if all_courses.has_previous %}
{#        如果有上一页，显示上一页，没有就不显示#}
        <li class="long"><a href="?{{ all_courses.previous_page_number.querystring }}">上一页</a> </li>
    {% endif %}

    {% for page in all_courses.pages %}
        {% if page %}
            {% ifequal page all_courses.number %}
{#                <span class="current page">{{ page }}</span>#}
                <span class="active">{{ page }}</span>
            {% else %}
                <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
            {% endifequal %}
        {% else %}
            <li class="none"><a href="">...</a> </li>
        {% endif %}
    {% endfor %}
    {% if all_courses.has_next %}
{#        <a href="?{{ page_obj.next_page_number.querystring }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a>#}
        <li class="long"><a href="?{{ all_courses.next_page_number.querystring }}">下一页</a> </li>
{#    {% else %}#}
{#        <span class="disabled next">{% trans "next" %} &rsaquo;&rsaquo;</span>#}
    {% endif %}
                        </ul>
                    </div>
				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">
                    {% for course in hot_courses %}

                    <dl>
						<dt>
							<a target="_blank" href="">
								<img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href=""><h2> {{ course.name }}</h2></a>
							<span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
{#                            注意显示难度等级方法#}
						</dd>
					</dl>
                     {% endfor %}
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

practice/templates/course-video.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}公开课视频信息{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li><a href="{% url 'courses:courses_list' %}">科目列表</a>></li>
                <li><a href="{% url 'courses:course_detail' course.id %}">课程详情</a>></li>
                <li>章节信息</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
        <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>

            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_times }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'courses:course_video' course.id %}"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="{% url 'courses:course_comment' course.id %}"><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a> </div>
                </div>

                <div class="mod-chapters">
                     {% for lesson in course.get_course_lessons %}
                        <div class="chapter chapter-active" >
                        <h3>
                            <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                        </h3>
                        <ul class="video">
                            {% for video in lesson.get_lesson_videos %}
                            <li>
                                <a target="_blank" href='{% url "courses:video_play" video.id %}' class="J-media-item studyvideo">
                                    {{ video.name }}（{{ video.play_times }}分钟）
                                    <i class="study-state"></i>
                                </a>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>
                     {% endfor %}

                </div>

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                        {% for resource in course_resource %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">
                                    下载</a>
                            </li>
                        {% endfor %}
                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">{{ course.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.you_need_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/11/540e57300001d6d906000338-240-135_n0L8vbw.jpg" alt="django与vuejs实战项目2">
                                            <span class="name autowrap">django与vuejs实战项目2</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/12/python面向对象.jpg" alt="python面向对象">
                                            <span class="name autowrap">python面向对象</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/12/python文件处理.jpg" alt="python文件处理">
                                            <span class="name autowrap">python文件处理</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/11/mysql.jpg" alt="django入门">
                                            <span class="name autowrap">django入门</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/12/mysql.jpg" alt="xadmin进阶开发">
                                            <span class="name autowrap">xadmin进阶开发</span>
                                        </a>
                                    </li>

                                </ul>
                            </div>
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                <ul class="other-list">
                                    <li class="curr">
                                        <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                            <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                            <span class="name autowrap">Java工程师</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>    </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>

{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
{% endblock %}

practice/templates/org-detail-teachers.html
{% extends 'org_base.html' %}
{% block  title%}机构讲师列表{% endblock %}
{% block page_title %}机构讲师{% endblock %}
{#{% block homepage %}<li class=""><a href="{% url 'org:org_home' course_org.id  %}">机构首页</a></li>{% endblock %}#}
{#{% block org_course %}<li class="active2"><a href="{% url 'org:org_course' course_org.id %}">机构课程</a></li>{% endblock %}#}
{% block right_form %}
    <div class="right companycenter layout" >
        <div class="head">
            <h1>机构讲师</h1>
        </div>
        <div class="messagelist">
            <div class=" butler_list butler-fav-box">
                {% for teacher in all_teachers %}
                <dl class="des users">
                    <dt>
                        <a href="">
                        <img width="100" height="100" class="scrollLoading" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                        </a>
                    </dt>
                    <dd>
                        <h1>
                            <a href="">
                            bobby<span class="key">已认证</span>
                            </a>
                        </h1>
                        <ul class="cont clearfix">
                            <li class="time">工作年限：<span>{{ teacher.work_years }}</span></li>
                            <li class="c7">课程数：<span>0</span></li>
                        </ul>
                    </dd>
                </dl>
                {% endfor %}


            </div>
        </div>
    </div>
{% endblock %}

practice/templates/send_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>发送页面</title>
</head>
<body>
<P>
    密码重置成功
</P>
</body>
</html>

practice/templates/usercenter-fav-org.html
{% extends 'usercenter_base.html' %}
{% load staticfiles %}
{% block title %}我的收藏{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的机构收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:my_fav_orgs' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:my_fav_teachers' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:my_fav_courses' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">

                    {% for org in user_fav_orgs %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:org_home' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:org_home' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{ org.address }}市</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}


                </div>
            </div>
        </div>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript">
    $(document).ready(function() {
        $('.delete jsDeleteFav_org').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'org:org_add_fav' %}",
                data: {
                    fav_type: 2,
                    fav_id: favid,
                    csrfmiddlewaretoken: '799Y6iPeEDNSGvrTu3noBrO4MBLv6enY'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
    });
    </script>
{% endblock %}
<!DOCTYPE html>
<html>